# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Testing"
  lane :tests do
    run_tests(workspace: "SampleApp.xcworkspace",
              devices: ["iPhone 11"],
              scheme: "SampleApp")
    xcov(
      workspace: "SampleApp.xcworkspace",
      scheme: "SampleApp",
      ignore_file_path: "fastlane/.xcovignore",
      output_directory: "fastlane/xcov_output",
      minimum_coverage_percentage: 5.0 )
  end
end
