name: SAPP

on: [pull_request]
 
jobs:
  test:
    name: SAPP Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: sh tests.sh
        env:
            DANGER_GITHUB_API_TOKEN: 85bb3f6f80131f4e66eded668ec25b205282a16c
