name: SAPP

on: [pull_request]
 
jobs:
  test:
    name: SAPP Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: sh tests.sh
        env:
            DANGER_GITHUB_API_TOKEN: 4062d9c91609a91d0eeb1ab254db7db49a1fb9bb
