name: SAPP

on: [pull_request]
 
jobs:
  test:
    name: SAPP Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: |
            gem install danger-xcov
            fastlane tests
            danger --fail-on-errors=true
        env:
            DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
